# Generated by Django 5.2.5 on 2025-08-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Idea',
        ),
    ]
