# Generated by Django 5.2.5 on 2025-08-14 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_rename_task_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('x_pos', models.IntegerField()),
                ('y_pos', models.IntegerField()),
                ('in_understand', models.BooleanField(default=False)),
                ('in_map', models.BooleanField(default=False)),
                ('info', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AssetInMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.ManyToManyField(to='ideas.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='tijuana_map')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.AddField(
            model_name='assetinmap',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.map'),
        ),
    ]
