# Generated by Django 5.2.5 on 2025-08-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_asset_assetinmap_map_delete_idea_assetinmap_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='x_pos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='y_pos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='map',
            name='width',
            field=models.FloatField(),
        ),
    ]
