# Generated by Django 5.2.5 on 2025-08-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_alter_asset_x_pos_alter_asset_y_pos_alter_map_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='marker_id',
            field=models.IntegerField(default=999),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
