# Generated by Django 5.2.5 on 2025-08-20 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_asset_marker_id_alter_asset_id_alter_asset_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost', max_digits=12, null=True)),
                ('size', models.CharField(blank=True, help_text='e.g., "20×40 m" or "800 m²"', max_length=100)),
                ('carbon_emission', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated kg CO₂e', max_digits=12, null=True)),
                ('has_context', models.BooleanField(default=False, help_text='Check if context applies')),
                ('context', models.TextField(blank=True)),
                ('primary_user', models.CharField(blank=True, help_text='Intended population / primary user', max_length=200)),
                ('usage_patterns', models.TextField(blank=True)),
                ('lighting_noise', models.TextField(blank=True, help_text='Lighting / noise considerations')),
                ('drainage_maintenance', models.TextField(blank=True, help_text='Drainage / maintenance requirements')),
                ('nearby_assets_40_miles', models.PositiveIntegerField(default=0, help_text='Count of similar assets within 40 miles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to='ideas.asset')),
            ],
            options={
                'verbose_name': 'Background info',
                'verbose_name_plural': 'Background infos',
            },
        ),
    ]
