# Generated by Django 5.2.5 on 2025-08-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_assetbackground'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetbackground',
            options={},
        ),
    ]
