# Generated by Django 5.2.5 on 2025-08-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_alter_assetbackground_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbackground',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetbackground',
            name='type_name',
            field=models.CharField(default='unspecified', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='ideas.assetbackground', verbose_name='type/background'),
        ),
    ]
