# Generated by Django 5.2.5 on 2025-08-20 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_remove_assetbackground_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbackground',
            name='type_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
