# Generated by Django 5.2.5 on 2025-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_alter_assetbackground_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetbackground',
            name='context',
        ),
        migrations.AlterField(
            model_name='assetbackground',
            name='carbon_emission',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated kt CO₂e', max_digits=12, null=True),
        ),
    ]
