# Generated by Django 5.2.5 on 2025-08-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_remove_assetbackground_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rotation',
            field=models.FloatField(default=0.0),
        ),
    ]
