# Generated by Django 5.2.5 on 2025-10-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_asset_rotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='physical_height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='asset',
            name='physical_width',
            field=models.FloatField(default=0.0),
        ),
    ]
