# Generated by Django 5.2.5 on 2025-10-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_asset_physical_height_asset_physical_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='bottom_left_lat',
            field=models.FloatField(default=0.0, help_text='Bottom-left corner latitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='bottom_left_lng',
            field=models.FloatField(default=0.0, help_text='Bottom-left corner longitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='bottom_right_lat',
            field=models.FloatField(default=0.0, help_text='Bottom-right corner latitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='bottom_right_lng',
            field=models.FloatField(default=0.0, help_text='Bottom-right corner longitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='config_version',
            field=models.CharField(default='1.0', help_text='Version identifier for configuration changes', max_length=50),
        ),
        migrations.AddField(
            model_name='map',
            name='top_left_lat',
            field=models.FloatField(default=0.0, help_text='Top-left corner latitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='top_left_lng',
            field=models.FloatField(default=0.0, help_text='Top-left corner longitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='top_right_lat',
            field=models.FloatField(default=0.0, help_text='Top-right corner latitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='top_right_lng',
            field=models.FloatField(default=0.0, help_text='Top-right corner longitude'),
        ),
        migrations.AddField(
            model_name='map',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='height',
            field=models.FloatField(help_text='Physical map height in cm'),
        ),
        migrations.AlterField(
            model_name='map',
            name='width',
            field=models.FloatField(help_text='Physical map width in cm'),
        ),
    ]
